spring:
  application:
    name: spirng-boot-rabbitmq-demo
  groovy:
    template:
      check-template-location: false
  rabbitmq:
    publisher-confirms: true
    publisher-returns: true
    host: 127.0.0.1
    port: 5672
    username: root
    password: root
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
logging:
  config: classpath:logback.groovy