spring:
  application:
    name: spirng-boot-rabbitmq-demo
  groovy:
    template:
      check-template-location: false
  rabbitmq:
    publisher-confirms: true
    publisher-returns: true
    host: 127.0.0.1
    port: 5672
    username: root
    password: root
    manager:
      startup-command: D:/Develop/RabbitMQ/rabbitmq_server-3.7.14/sbin/rabbitmq-server.bat -detached
      shutdown-command: D:/Develop/RabbitMQ/rabbitmq_server-3.7.14/sbin/rabbitmqctl.bat stop
      status-command: D:/Develop/RabbitMQ/rabbitmq_server-3.7.14/sbin/rabbitmqctl.bat status
springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs
logging:
  config: classpath:logback.groovy